name: Pipeline

on:
  push:
    branches: 
      - main
    
jobs:
  test:
    uses: mastrasec/firewow/.github/workflows/test.yaml@main

  spdx:
    uses: mastrasec/firewow/.github/workflows/spdx.yaml@main
